version: "3"
services:
  grunt:
    image: grunt
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/sh
    tty: true
    volumes:
      - .:/app
    networks:
      - elastic
    depends_on:
      - es

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge