---
user: www-data
group: www-data
pid: /Users/Daniel/RubymineProjects/grunt/tmp/pids/thin.pid
timeout: 30
wait: 30
log: /Users/Daniel/RubymineProjects/grunt/logs/thin.log
max_conns: 1024
require: ['/Users/Daniel/RubymineProjects/grunt/config.ru']
environment: development
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
#socket: /Users/Daniel/RubymineProjects/grunt/tmp/sockets/thin.sock
chdir: /Users/Daniel/RubymineProjects/grunt
tag: thin-elasticsearch aux